nav:
  - Home: index.md
  - Overview: 00-overview/README.md
  - Intents & Routing: 10-intents-routing/README.md
  - KG Schema: 20-kg-schema/README.md
  - Agents & MCP: 30-agents-mcp/README.md
  - Retrieval: 40-retrieval-verification/README.md
  - Contact Flows: 50-contact-flows/README.md  # If this exists
  - Architecture: 60-architecture/README.md
  - Tech Stack: 70-tech-stack-infra/README.md
  - Security: 80-security-privacy/README.md
  - Roadmap: 90-roadmap-slo/README.md
