site_name: Toll Aviation Chatbot Plan

nav:
  - Overview: 00-overview/README.md
  - Intents & Routing: 10-intents-routing/README.md
  - KG Schema: 20-kg-schema/README.md
  - Agents & MCP: 30-agents-mcp/README.md
  - Retrieval & Verification: 40-retrieval-verification/README.md
  - Contact Flows: 50-contact-flows/README.md
  - Architecture: 60-architecture/README.md
  - Tech & Infra: 70-tech-stack-infra/README.md
  - Security & Privacy: 80-security-privacy/README.md
  - Roadmap & SLOs: 90-roadmap-slo/README.md

theme:
  name: material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
